# Generated by Django 4.1.2 on 2022-11-19 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymclasses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 19, 0, 53, 35, 6392, tzinfo=datetime.timezone.utc)),
        ),
    ]
