# Generated by Django 4.1.3 on 2022-11-04 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='studio_imgs',
        ),
        migrations.AddField(
            model_name='imagerep',
            name='studio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studios.studio'),
            preserve_default=False,
        ),
    ]
